### ISSUE TITLE
Wrong byte count for language 05AB1E in "Will Jimmy fall off his platform?"

### ISSUE THREAD

**Issue by Jakuje** [xMikee1/ppcg-leaderboard#1]
The following leaderboard shows wrong byte count for this language. I actually do not see what is the actual problem in the regex, but I think it should not scan through the language name (whole line), but start just after that.

https://codegolf.stackexchange.com/questions/187586/will-jimmy-fall-off-his-platform/187615#187615

https://xmikee1.github.io/ppcg-leaderboard/?id=187586

**Comment by xMikee1** [comment]
To parse the number out of the HTML title the following regex is used:

`(-?\d+)\D*<\/h\d>`

That regex finds the last number in the string. The problem is that for languages like 05AB1E, it is necessary to include the codepage as a reference for the byte count for each character. What happens is that when we have HTML like this:

`<h1><a href=\"https://github.com/Adriandmen/05AB1E/wiki/Commands\" rel=\"nofollow noreferrer\">05AB1E (legacy)</a>, <s>9</s> <s>8</s> 7 <a href=\"https://github.com/Adriandmen/05AB1E/wiki/Codepage\" rel=\"nofollow noreferrer\">bytes</a></h1>`

The regex recognizes `1` as the last number in the string because it is in the URL for the codepage. An alternative would be to put the codepage on the next line, but that's a lot to ask of everybody who programs in 05AB1E.

Anyways, probably the next steps would be to design a smarter regex that can detect and consume any links containing numbers. I spent about half an hour trying to design one but to no avail. If anybody can find a better regex or wants to refactor the number part of the parsing, feel free to submit a PR.

I will continue to work on it and try to find a better solution.

**Comment by xMikee1** [comment]
This issue was solved by https://github.com/xMikee1/ppcg-leaderboard/pull/2.
